CREATE TABLE keywords (
	id SERIAL PRIMARY KEY,
	name VARCHAR UNIQUE NOT NULL,
	chan VARCHAR UNIQUE NOT NULL
);

CREATE TABLE entries (
	id SERIAL PRIMARY KEY,
	keyword_id INT NOT NULL REFERENCES keywords ON DELETE CASCADE,
	idx INT NOT NULL,
	creation_ts TIMESTAMP NOT NULL,
	created_by VARCHAR NOT NULL
);
